export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_RSS_LIST = 'SAVE_RSS_LIST';
export const SET_RSS_DATA = 'SET_RSS_DATA';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const TOGGLE_LOADING_STATE = 'TOGGLE_LOADING_STATE';
