
export const SAVE_CURRENT_CHANNEL = 'SAVE_CURRENT_CHANNEL';
export const SET_RSS_DATA = 'SET_RSS_DATA';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const TOGGLE_LOADING_STATE = 'TOGGLE_LOADING_STATE';
export const SAVE_CURRENT_MESSAGE = 'SAVE_CURRENT_MESSAGE';
